# Generated by Django 3.2.6 on 2021-08-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MnemGen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='WordList',
        ),
    ]
