# Generated by Django 3.2.6 on 2021-08-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MnemGen', '0002_rename_words_wordlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordList',
            new_name='WordListEntry',
        ),
    ]
